name: PR-pipeline_torchtitan-npu

concurrency:
  max: 3
  exceed-action: QUEUE
  enable: true
  preemption:
    enable: true
    events: [mr_id]

on:
  pull_request_comment:
    types: [created]
    branches: [ '*' ]
    comments: [ '^(?:\/)?compile*' ]
  pr_comment:
    types: [ created ]
    keyword: '^(?:\/)?compile*'

env:
  org_name: "${{ vars.ORG_NAME }}"
  repo_name: ${{atomgit.event.repository.name}}
  MERGE_ID: ${{atomgit.event.pull_request.number}}
  TARGET_BRANCH: ${{atomgit.base_ref}}
  SOURCE_BRANCH: ${{atomgit.head_ref}}
  obs_path: "${{ env.org_name }}/${{ env.repo_name }}/ci/package/${{ env.MERGE_ID }}"
  obs_smoke_path: "${{ env.obs_path }}/presmoke/2"
  online: ${{ vars.APPLY_LABEL }}

stages:
  stage1:
    name: PreBuild
    jobs:
      JOB_image:
        name: Test_image
        steps:
          - name: revise_image
            identifier: revise_image
            uses: cann/.gitcode/actions/revise-img@master
            with:
              repo_name: ${{ env.repo_name }}
              target_branch: ${{ env.TARGET_BRANCH }}
              repo_url: ${{ vars.CI_PATH }}
          -
            name: show_output
            run: |
              echo "Compile_Ascend_X86: ${{ steps.revise_image.outputs.Compile_Ascend_X86 }}"
        runs-on: ["self-hosted", "arch=x64", "spec=small"]
        container:
          image: swr.cn-north-4.myhuaweicloud.com/ci_cann/ubuntu20.04.05_x86:k8s_v1.1006
      JOB_pre:
        name: Test_PreBuild
        uses: cann/.gitcode/.gitcode/workflows/pre_action.yml@master
    pre:
    - type: auto
    fail-fast: true

  stage2:
    name: Compile
    jobs:
      JOB_CodeCheck:
        name: CodeCheck
        uses: .gitcode/workflows/codecheck_action.yml
        with:
          precommit_image_version: ubuntu24.04_x86_64:wdy05
          codecheck_image_version: ${{ jobs.JOB_image.outputs.codecheck }}
      JOB_staticcheck_md_check:
        name: CodeCheck_staticcheck_md_check
        uses: .gitcode/workflows/staticcheck_action.yml
        with:
          check_type: 'md_check'
          image_version: ${{ jobs.JOB_image.outputs.staticcheck }}
    pre:
    - type: auto
    fail-fast: true
  stage3:
    name: UT
    jobs:
      JOB_UT_Test:
        name: UT_Test
        uses: .gitcode/workflows/llt_action.yml
        with:
          ut_type: 'torchtitan-npu'
          ut_package: 'ut_cov_torchtitan-npu.tar.gz'
          image_version: ${{ jobs.JOB_image.outputs.UT_Test }}
    pre:
    - type: auto
    fail-fast: true
  stage4:
    name: PreSmoke
    jobs:
      PreSmoke_A3:
        name: PreSmoke_A3
        steps:
          -
            name: Checkout
            identifier: process_checkout
            uses: checkout
            with:
              ref: ${{ atomgit.event.pull_request.merge_commit_sha }}
              token: ${{secrets.GIT_TOKEN}}
          -
            name: download pr files
            uses: obs-download
            with:
              endpoint: "https://obs.cn-north-4.myhuaweicloud.com"
              bucket: "ascend-ci"
              access-key: ${{ secrets.AK }}
              secret-key: ${{ secrets.SK }}
              key: |
                ${{ env.obs_path }}/pr_filelist.txt
                ${{ env.obs_path }}/pr_filelist_mod.txt
                ${{ env.obs_path }}/update_file_detail.txt
                ${{ env.obs_path }}/torchtitan-npu_smoke.sh
              path: ${{ steps.process_checkout.outputs.path }}
          -
            name: smoke executor
            timeout-minutes: 30
            run: |
              set -e
              export WORKSPACE=${{ steps.process_checkout.outputs.path }}
              export repo_name=${{env.repo_name}}
              export obs_path=${{env.obs_path}}
              export obs_smoke_path=${{ env.obs_smoke_path }}
              export pr_id=${{ env.MERGE_ID }}
              export AK=${{secrets.AK}}
              export SK=${{secrets.SK}}
              bash ${{ steps.process_checkout.outputs.path }}/torchtitan-npu_smoke.sh
        if: env.TARGET_BRANCH == 'master'
        runs-on: ['self-hosted','npu=4','smoke=301']
        container:
          image: swr.cn-north-4.myhuaweicloud.com/ci_cann/${{ jobs.JOB_image.outputs.PreSmoke_A900_npupool }}
    pre:
      - type: auto
    fail-fast: true
post:
  jobs:
    job_post:
      name: Test_post
      uses: cann/.gitcode/.gitcode/workflows/post_action.yml@master
